package:
  name: tracking
  version: 0.1
  
source:
  path: ../

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    
about:
  summary: 'read and write zarr files'
  description: 'read and write zarr files'

extra:
  recipe-maintainers:
    - phaustin

